name: Deploy MySQL Container

on:
  push:
    branches:
      - deploy

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test workflow
        run: echo "GitHub Actions funcionando correctamente"
